### ISSUE TITLE
General Responsive issues

### ISSUE THREAD

**Issue by SKBruck** [arsmentis/arsmentis#25]
* Client Page is not responsive - #43
* Navigation menu is poorly responsive (Phase 2)
* Contact has own issue - #22

**Comment by SKBruck** [comment]
Explaining no min-width on IE: IE browsers can be resized to small enough resolutions that a horizontal scroll bar appears. Other browsers only minimize to the min-width I've set in the css.

**Comment by artlogic** [comment]
What about the client screenshot bullet?

**Comment by SKBruck** [comment]
The Client Screenshot bullet is about figuring out the alignment of the screenshots with the header and paragraph texts at smaller resolutions. This issue is referenced in the Client Screenshot issue.

**Comment by artlogic** [comment]
That is, in issue #10.

**Comment by SKBruck** [comment]
All fixed with exception of contact form - has its own issue (#22) so closing this one.
