### ISSUE TITLE
CSS for Printing

### ISSUE THREAD

**Issue by SKBruck** [arsmentis/arsmentis#26]
"Create passable css for printing after the launch. We'll at least want to have the logo show up as an H1."

**Comment by SKBruck** [comment]
We discussed this being addressed during Phase 2, but I can also see if I can get the print.css working for the current site. Would you like me to do that?

**Comment by artlogic** [comment]
Let's put it off until phase 2.

**Comment by SKBruck** [comment]
Ok - sounds good.

**Comment by SKBruck** [comment]
Closing; addressed by: https://github.com/arsmentis/arsmentis-jekyll/issues/8
