### ISSUE TITLE
Phase 2: Simplify theme

### ISSUE THREAD

**Issue by SKBruck** [arsmentis/arsmentis#41]
Phase 2 consists of remaking the arsmentis theme without using another theme as the base ("from scratch"). The purpose of phase 2 is to clean up and simplify the theme now that a design is complete.

May involve/resolve issues: #10, #22, #25, #26, #29, and #30 

Anything to add?

**Comment by artlogic** [comment]
It might be worthwhile to take a look at [Jekyll](http://jekyllrb.com/) and [Octopress 3](https://github.com/octopress/octopress) before deciding to stick with Octopress 2.

**Comment by SKBruck** [comment]
Ok - sounds good. We should talk about it soon. I've got this break coming up, and I'm about 75% done with my assignments, so I'll have the week mostly free from school duties.

**Comment by SKBruck** [comment]
Will be fixed by following issues in arsmentis-jekyll repo:
https://github.com/arsmentis/arsmentis-jekyll/issues/5
https://github.com/arsmentis/arsmentis-jekyll/issues/5
